### ISSUE TITLE
Missing contacts causes AttributeError exception

### ISSUE THREAD

**Issue by tmuncks** [InternetNZ/pyepp#56]
**Describe the bug**
We are supposed to have all contacts populated for all domains, but for historic reasons, this is not always the case. When we hit one of the domains that is missing a contact, `Domain().info()` throws an exception:
```
Traceback (most recent call last):
  File "/home/thms/projects/epp/test.py", line 33, in <module>
    domain_check = domain.info('redacted.gl')
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/thms/projects/epp/venv/lib64/python3.11/site-packages/pyepp/domain.py", line 167, in info
    'admin': raw_response.find('contact', {'type': 'admin'}).text,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
```

**To Reproduce**
This is the real life (redacted) `raw_response` from a domain that causes this error. It it simply missing one or more expected contacts.

```
<?xml version="1.0" encoding="utf-8"?>
<epp xmlns="urn:ietf:params:xml:ns:epp-1.0">
    <response>
        <result code="1000">
            <msg>Command completed successfully.</msg>
        </result>
        <resData>
            <domain:infData xmlns:domain="urn:ietf:params:xml:ns:domain-1.0">
                <domain:name>redacted.gl</domain:name>
                <domain:roid>D327749188-CNIC</domain:roid>
                <domain:status s="clientTransferProhibited"/>
                <domain:registrant>REDACTED</domain:registrant>
                <domain:contact type="tech">REDACTED</domain:contact>
                <domain:ns>
                    <domain:hostObj>rajeev.ns.cloudflare.com</domain:hostObj>
                    <domain:hostObj>chin.ns.cloudflare.com</domain:hostObj>
                </domain:ns>
                <domain:clID>REDACTED</domain:clID>
                <domain:crID>REDACTED</domain:crID>
                <domain:crDate>2012-02-08T07:25:36.0Z</domain:crDate>
                <domain:upDate>2023-08-31T17:00:37.0Z</domain:upDate>
                <domain:exDate>2024-02-08T23:59:59.0Z</domain:exDate>
            </domain:infData>
        </resData>
        <extension>
            <secDNS:infData xmlns:secDNS="urn:ietf:params:xml:ns:secDNS-1.1">
                <secDNS:dsData>
                    <secDNS:keyTag>2371</secDNS:keyTag>
                    <secDNS:alg>13</secDNS:alg>
                    <secDNS:digestType>2</secDNS:digestType>
                    <secDNS:digest>9A60356B6BEC4EE4FAA1428B3C4D6DCF6A6B22B4A70BCDB11891B2D7D52560B2</secDNS:digest>
                </secDNS:dsData>
            </secDNS:infData>
        </extension>
    <trID>
        <clTRID>a65cc052-38a3-4df2-ad0e-245f8fe2c45d</clTRID>
        <svTRID>CNIC-F8932D0CCF57BA5E0D72CE01BAF69E992CF83EA792B9249BD07F7287A4B</svTRID>
    </trID>
    </response>
</epp>
```

**Expected behaviour**
Even though we expect all contacts to be present, we should not "crash" when they are missing. Instead we should return a valid result, with these contacts set to None or something similar.

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Version 38

**Python version**
 - Python 3.11.5

**Additional context**
Running from a venv with only pyepp installed

**Comment by tmuncks** [comment]
Fantastic! Thank you!
